### ISSUE TITLE
tests installed under test/

### ISSUE THREAD

**Issue by dschwoerer** [boutproject/boututils#9]
If the tests are installed, they should go under `boututils/test` rather then `test`

Currently this results in conflicts with `boutdata`:
```
Error: Transaction test error:
  file /usr/lib/python3.9/site-packages/test/__pycache__/__init__.cpython-39.opt-1.pyc conflicts between attempted installs of python3-boutdata-0.1.2-1.fc33.noarch and python3-boututils-0.1.4-1.fc33.noarch
  file /usr/lib/python3.9/site-packages/test/__pycache__/__init__.cpython-39.pyc conflicts between attempted installs of python3-boutdata-0.1.2-1.fc33.noarch and python3-boututils-0.1.4-1.fc33.noarch
  file /usr/lib/python3.9/site-packages/test/__pycache__/test_import.cpython-39.opt-1.pyc conflicts between attempted installs of python3-boutdata-0.1.2-1.fc33.noarch and python3-boututils-0.1.4-1.fc33.noarch
  file /usr/lib/python3.9/site-packages/test/__pycache__/test_import.cpython-39.pyc conflicts between attempted installs of python3-boutdata-0.1.2-1.fc33.noarch and python3-boututils-0.1.4-1.fc33.noarch
  file /usr/lib/python3.9/site-packages/test/test_import.py conflicts between attempted installs of python3-boutdata-0.1.2-1.fc33.noarch and python3-boututils-0.1.4-1.fc33.noarch
```

**Comment by loeiten** [comment]
Is this related #2?

I'm in favour of keeping them in `/tests` as this keeps a clear boundary between the project package and test. However, there seem to be a several accepted places to keep the test files, so there are there any benefits to move them to `boututils/test`?

I'm able to install and import the packages on `python 3.8.2` on `ubuntu:20.04`. Is the error related to `python 3.9`?

**Comment by dschwoerer** [comment]
No, I don't think it is related to #2 

How are you installing them?
I used rpm, which does not overwrite files from other packages, while pip just overwrites conflicting files, and you end up with the last installed file, giving you hard to reproduce setups, as you not only have to care about what is installed, but in what order files have been installed.

If the files are intended to be installed, they shouldn't be in such a generic place as `test`.

**Comment by johnomotani** [comment]
It seems to be fairly standard to keep the tests in a directory like `boututils/tests`. See e.g. [xarray](https://github.com/pydata/xarray/tree/master/xarray) and [numpy](https://github.com/numpy/numpy). It also seems to play well with `setuptools` (see https://setuptools.readthedocs.io/en/latest/setuptools.html#using-find-packages), e.g. just
```
from setuptools import find_packages
...
packages = find_packages()
```
in `setup.py` or
```
packages = find:
```
in `setup.cfg`

I think it's good to install the tests (even if they don't do much now) so they get distributed through PyPi, etc. Moving them under `boututils/tests/` seems like the simplest way of doing that, rather than having some more complicated configuration in `setup.py`.

**Comment by loeiten** [comment]
Never realised that it's a good idea to port the tests with the package (for example to debug on end-user side). I'll make a PR
